/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Box0RouteImport } from './routes/_box0'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Box0WorkspacesRouteImport } from './routes/_box0/workspaces'
import { Route as Box0UsersRouteImport } from './routes/_box0/users'
import { Route as Box0TasksRouteImport } from './routes/_box0/tasks'
import { Route as Box0MachinesRouteImport } from './routes/_box0/machines'
import { Route as Box0AgentsRouteImport } from './routes/_box0/agents'
import { Route as Box0TasksTaskIdRouteImport } from './routes/_box0/tasks.$taskId'
import { Route as Box0MachinesMachineIdRouteImport } from './routes/_box0/machines.$machineId'
import { Route as Box0AgentsNameRouteImport } from './routes/_box0/agents.$name'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Box0Route = Box0RouteImport.update({
  id: '/_box0',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Box0WorkspacesRoute = Box0WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => Box0Route,
} as any)
const Box0UsersRoute = Box0UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => Box0Route,
} as any)
const Box0TasksRoute = Box0TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => Box0Route,
} as any)
const Box0MachinesRoute = Box0MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => Box0Route,
} as any)
const Box0AgentsRoute = Box0AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => Box0Route,
} as any)
const Box0TasksTaskIdRoute = Box0TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => Box0TasksRoute,
} as any)
const Box0MachinesMachineIdRoute = Box0MachinesMachineIdRouteImport.update({
  id: '/$machineId',
  path: '/$machineId',
  getParentRoute: () => Box0MachinesRoute,
} as any)
const Box0AgentsNameRoute = Box0AgentsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => Box0AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agents': typeof Box0AgentsRouteWithChildren
  '/machines': typeof Box0MachinesRouteWithChildren
  '/tasks': typeof Box0TasksRouteWithChildren
  '/users': typeof Box0UsersRoute
  '/workspaces': typeof Box0WorkspacesRoute
  '/agents/$name': typeof Box0AgentsNameRoute
  '/machines/$machineId': typeof Box0MachinesMachineIdRoute
  '/tasks/$taskId': typeof Box0TasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agents': typeof Box0AgentsRouteWithChildren
  '/machines': typeof Box0MachinesRouteWithChildren
  '/tasks': typeof Box0TasksRouteWithChildren
  '/users': typeof Box0UsersRoute
  '/workspaces': typeof Box0WorkspacesRoute
  '/agents/$name': typeof Box0AgentsNameRoute
  '/machines/$machineId': typeof Box0MachinesMachineIdRoute
  '/tasks/$taskId': typeof Box0TasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_box0': typeof Box0RouteWithChildren
  '/login': typeof LoginRoute
  '/_box0/agents': typeof Box0AgentsRouteWithChildren
  '/_box0/machines': typeof Box0MachinesRouteWithChildren
  '/_box0/tasks': typeof Box0TasksRouteWithChildren
  '/_box0/users': typeof Box0UsersRoute
  '/_box0/workspaces': typeof Box0WorkspacesRoute
  '/_box0/agents/$name': typeof Box0AgentsNameRoute
  '/_box0/machines/$machineId': typeof Box0MachinesMachineIdRoute
  '/_box0/tasks/$taskId': typeof Box0TasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agents'
    | '/machines'
    | '/tasks'
    | '/users'
    | '/workspaces'
    | '/agents/$name'
    | '/machines/$machineId'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agents'
    | '/machines'
    | '/tasks'
    | '/users'
    | '/workspaces'
    | '/agents/$name'
    | '/machines/$machineId'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_box0'
    | '/login'
    | '/_box0/agents'
    | '/_box0/machines'
    | '/_box0/tasks'
    | '/_box0/users'
    | '/_box0/workspaces'
    | '/_box0/agents/$name'
    | '/_box0/machines/$machineId'
    | '/_box0/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Box0Route: typeof Box0RouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_box0': {
      id: '/_box0'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Box0RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_box0/workspaces': {
      id: '/_box0/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof Box0WorkspacesRouteImport
      parentRoute: typeof Box0Route
    }
    '/_box0/users': {
      id: '/_box0/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof Box0UsersRouteImport
      parentRoute: typeof Box0Route
    }
    '/_box0/tasks': {
      id: '/_box0/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof Box0TasksRouteImport
      parentRoute: typeof Box0Route
    }
    '/_box0/machines': {
      id: '/_box0/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof Box0MachinesRouteImport
      parentRoute: typeof Box0Route
    }
    '/_box0/agents': {
      id: '/_box0/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof Box0AgentsRouteImport
      parentRoute: typeof Box0Route
    }
    '/_box0/tasks/$taskId': {
      id: '/_box0/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof Box0TasksTaskIdRouteImport
      parentRoute: typeof Box0TasksRoute
    }
    '/_box0/machines/$machineId': {
      id: '/_box0/machines/$machineId'
      path: '/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof Box0MachinesMachineIdRouteImport
      parentRoute: typeof Box0MachinesRoute
    }
    '/_box0/agents/$name': {
      id: '/_box0/agents/$name'
      path: '/$name'
      fullPath: '/agents/$name'
      preLoaderRoute: typeof Box0AgentsNameRouteImport
      parentRoute: typeof Box0AgentsRoute
    }
  }
}

interface Box0AgentsRouteChildren {
  Box0AgentsNameRoute: typeof Box0AgentsNameRoute
}

const Box0AgentsRouteChildren: Box0AgentsRouteChildren = {
  Box0AgentsNameRoute: Box0AgentsNameRoute,
}

const Box0AgentsRouteWithChildren = Box0AgentsRoute._addFileChildren(
  Box0AgentsRouteChildren,
)

interface Box0MachinesRouteChildren {
  Box0MachinesMachineIdRoute: typeof Box0MachinesMachineIdRoute
}

const Box0MachinesRouteChildren: Box0MachinesRouteChildren = {
  Box0MachinesMachineIdRoute: Box0MachinesMachineIdRoute,
}

const Box0MachinesRouteWithChildren = Box0MachinesRoute._addFileChildren(
  Box0MachinesRouteChildren,
)

interface Box0TasksRouteChildren {
  Box0TasksTaskIdRoute: typeof Box0TasksTaskIdRoute
}

const Box0TasksRouteChildren: Box0TasksRouteChildren = {
  Box0TasksTaskIdRoute: Box0TasksTaskIdRoute,
}

const Box0TasksRouteWithChildren = Box0TasksRoute._addFileChildren(
  Box0TasksRouteChildren,
)

interface Box0RouteChildren {
  Box0AgentsRoute: typeof Box0AgentsRouteWithChildren
  Box0MachinesRoute: typeof Box0MachinesRouteWithChildren
  Box0TasksRoute: typeof Box0TasksRouteWithChildren
  Box0UsersRoute: typeof Box0UsersRoute
  Box0WorkspacesRoute: typeof Box0WorkspacesRoute
}

const Box0RouteChildren: Box0RouteChildren = {
  Box0AgentsRoute: Box0AgentsRouteWithChildren,
  Box0MachinesRoute: Box0MachinesRouteWithChildren,
  Box0TasksRoute: Box0TasksRouteWithChildren,
  Box0UsersRoute: Box0UsersRoute,
  Box0WorkspacesRoute: Box0WorkspacesRoute,
}

const Box0RouteWithChildren = Box0Route._addFileChildren(Box0RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Box0Route: Box0RouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
